# Điểm
# 61.4900
# Đã chấm 2 phút trước

# Chỉ số

# ers
# 61.49
# f_delta
# 1
# penalty
# 1
# final_score
# 61.49
# total_count
# 420
# ttft_p50_ms
# 45
# ttft_p95_ms
# 65
# failed_count
# 5
# warmup_count
# 0
# accuracy_drop
# 0
# tbt_median_ms
# 4
# tokens_per_sec
# 0.0577
services:
  model:
    image: misokaio/ghfjdk:v0.25.1
    environment:
    - HF_HUB_OFFLINE=1
    - TRANSFORMERS_OFFLINE=1
    - VLLM_USE_FASTOKENS=1
    - VLLM_CONFIGURE_LOGGING=0
    entrypoint:
      - python3 #Don't change this to vllm-server
      - -m  #Don't change this to vllm-server
      - vllm.entrypoints.openai.api_server #Don't change this to vllm-server
    command:
      - --model=/model
      - --quantization=fp8          # native online bf16->fp8 (H200 coherent, no temp)
      - --served-model-name=LFM2.5-1.2B-Instruct
      - --host=0.0.0.0
      - --port=8000
      - --max-model-len=5888
      - --optimization-level=3
      - --gpu-memory-utilization=0.85
      - --tensor-parallel-size=1
      - --enable-prefix-caching
      - --enable-chunked-prefill
      # - --performance-mode=interactivity
      - --max-num-batched-tokens=11776
      - --max-num-seqs=32
      - --disable-uvicorn-access-log
      - --language-model-only
      - --skip-mm-profiling
      - --no-enable-log-requests
      - --disable-log-stats
    ports:
      - "8000:8000"
    shm_size: "2g"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
