FROM misokaio/ghfjdk@sha256:fdc694b7282a591428debbcbb9ae2424bfb5c2905d7950f536c13495a04ac829

ENV VLLM_LFM25_FUSED_SHORTCONV_FP8_OUT=1

COPY apply_lfm25_shortconv_fp8_out.py /tmp/apply_lfm25_shortconv_fp8_out.py
COPY lfm25_fused_shortconv_fp8_out.py /tmp/lfm25_fused_shortconv_fp8_out.py
COPY test_lfm25_fused_shortconv_fp8_out.py /opt/lfm25/test_lfm25_fused_shortconv_fp8_out.py

RUN python3 /tmp/apply_lfm25_shortconv_fp8_out.py \
      --kernel-source /tmp/lfm25_fused_shortconv_fp8_out.py \
    && python3 -m py_compile \
      /tmp/apply_lfm25_shortconv_fp8_out.py \
      /tmp/lfm25_fused_shortconv_fp8_out.py \
      /opt/lfm25/test_lfm25_fused_shortconv_fp8_out.py \
    && rm -f \
      /tmp/apply_lfm25_shortconv_fp8_out.py \
      /tmp/lfm25_fused_shortconv_fp8_out.py
